quarkus.http.cors=true
credentials.file-path=/credentials.json
#credentials.user=<your_google_user>
spreadsheet-id=1XRFxx2c4Ffkw3LB10TbRbI7R1YJdJ7Q574LF_oEH5nI
quarkus.rest-client.bcb-ptax-api.url=https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata
